services:
    redpanda: # expose ports when needed for minecraft mod
        image: redpandadata/redpanda:latest
        container_name: skyblock-redpanda
        command: >
            redpanda start
            --overprovisioned
            --smp 1
            --memory 512M
            --reserve-memory 0M
            --node-id 0
            --check=false
            --kafka-addr PLAINTEXT://0.0.0.0:9092
            --advertise-kafka-addr PLAINTEXT://redpanda:9092
        networks:
            - skyblock-backend

    postgres_db:
        image: postgres:15.3-alpine
        container_name: skyblock-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-skyblock_db}
            POSTGRES_USER: ${POSTGRES_USER:-skyblock_user}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-super_secure_password123}
        ports:
            - "127.0.0.1:5432:5432" # optional, local access only
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - skyblock-backend

    updater:
        build:
            context: .
            dockerfile: services/skyblock-updater/Dockerfile
        container_name: skyblock-updater
        depends_on:
            - redpanda
            - postgres_db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/${POSTGRES_DB:-skyblock_db}
            SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-skyblock_user}
            SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-super_secure_password123}
            SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
            SPRING_APPLICATION_JSON: >
                {
                  "logging.level.root": "INFO",
                  "logging.level.org.apache.kafka": "WARN",
                  "logging.level.org.springframework.kafka": "WARN",
                  "logging.level.io.github.jaron2668": "INFO"
                }
        networks:
            - skyblock-backend

    #sniper: # not finished rn
    #  build:
    #    context: .
    #    dockerfile: SkyblockSniper/Dockerfile
    #  container_name: skyblock-sniper
    #  depends_on:
    #    - redpanda
    #    - postgres_db
    #  environment:
    #    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/${POSTGRES_DB:-skyblock_db}
    #    SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-skyblock_user}
    #    SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-super_secure_password123}
    #    SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
    #  networks:
    #    - skyblock-backend

    flipper: # not finished rn
        build:
            context: .
            dockerfile: services/skyblock-flipper/Dockerfile
        container_name: skyblock-flipper
        depends_on:
            - redpanda
            - postgres_db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/${POSTGRES_DB:-skyblock_db}
            SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-skyblock_user}
            SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-super_secure_password123}
            SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
        networks:
            - skyblock-backend

volumes:
    pgdata:

networks:
    skyblock-backend:
